
// This file is generated by the Snaplet CLI
export type JsonPrimitive = null | number | string | boolean

export type NestedArray<V> = Array<V | NestedArray<V>>

export type Nested<V> = V | { [s: string]: V | Nested<V> } | Array<V | Nested<V>>

export type Json = Nested<JsonPrimitive>

export type Structure = {
  $schemas: ["public"],
  "public": {
  $tables: [],
  
},
}





interface Schema_public {

}

export interface Database {
  public: Partial<Schema_public>
}

export type TransformContext = {
  structure: Structure;
}

export type Transform = (ctx: TransformContext) => (Partial<Database> | Promise<Partial<Database>>)
